version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: finwise-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: finwise
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: finwise-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@finwise.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  postgres_data: